from flask import Flask, request, jsonify, send_from_directory
import json
import os
import logging
import time

# Configure logging
logging.basicConfig(level=logging.INFO)

app = Flask(__name__)

DATA_FILE = "/data/endpoints.json"

def load_data():
    if not os.path.exists(DATA_FILE):
        return []
    try:
        with open(DATA_FILE, "r") as f:
            return json.load(f)
    except:
        return []

def save_data(data):
    os.makedirs("/data", exist_ok=True)
    with open(DATA_FILE, "w") as f:
        json.dump(data, f)

def generate_pjsip(endpoints):
    """Generates a separate config file for custom endpoints."""
    config = "; Custom endpoints generated by Management API\n"
    
    for ep in endpoints:
        user = str(ep.get("username") or "")
        pwd = str(ep.get("password") or "")

        if not user:
            continue

        config += f"""
[{user}]
type=endpoint
context=default
disallow=all
allow=opus,ulaw,alaw
webrtc=yes
dtls_auto_generate_cert=yes
ice_support=yes
media_encryption=dtls
dtls_verify=fingerprint
dtls_setup=actpass
auth={user}
aors={user}
transport=transport-ws

[{user}]
type=auth
auth_type=userpass
username={user}
password={pwd}

[{user}]
type=aor
max_contacts=5
remove_existing=yes
"""

    try:
        os.makedirs("/data", exist_ok=True)
        with open("/data/custom_endpoints.conf", "w") as f:
            f.write(config)
        logging.info("Updated /data/custom_endpoints.conf")
        return True
    except Exception as e:
        logging.error(f"Failed to write custom config: {e}")
        return False

def generate_extensions():
    os.makedirs("/etc/asterisk", exist_ok=True)
    with open("/etc/asterisk/extensions.conf", "w") as f:
        f.write("""
[default]
exten => _X.,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
""")
    logging.info("Generated extensions.conf")

@app.route("/")
def index():
    return send_from_directory("/app/public", "index.html")

@app.route("/api/endpoints", methods=["GET"])
def get_endpoints():
    return jsonify(load_data())

@app.route("/api/endpoints", methods=["POST"])
def save_endpoints():
    try:
        data = request.get_json(force=True)

        logging.info(f"Received endpoints: {data}")

        if not isinstance(data, list):
            return jsonify({"success": False, "error": "Invalid format"})

        # Save JSON
        save_data(data)

        # Generate custom config and reload Asterisk
        if generate_pjsip(data):
            # SAFE RELOAD: Avoids killing the process/triggering S6 loops
            logging.info("Reloading Asterisk PJSIP...")
            os.system("asterisk -rx 'pjsip reload'")
            os.system("asterisk -rx 'dialplan reload'")
            
            return jsonify({"success": True, "message": "Updated and reloaded custom endpoints"})
        else:
            return jsonify({"success": False, "error": "Failed to update configuration"})

    except Exception as e:
        logging.error(f"Error: {e}")
        return jsonify({"success": False, "error": str(e)})

# IMPORTANT: static file handler
@app.route("/<path:path>")
def static_files(path):
    return send_from_directory("/app/public", path)

if __name__ == "__main__":
    # Ensure baseline configs exist on startup
    endpoints = load_data()
    generate_pjsip(endpoints)
    # Note: we don't overwrite extensions.conf dynamically anymore to stay stable
    
    app.run(host="0.0.0.0", port=8090)
