const express = require('express');
const fs = require('fs');
const { exec } = require('child_process');
const path = require('path');

const app = express();
app.use(express.json());

// Expose public folder
app.use(express.static(path.join(__dirname, 'public')));

// Use relative API paths for HA Ingress compatibility
const DATA_DIR = '/data';
const ENDPOINTS_FILE = path.join(DATA_DIR, 'endpoints.json');
const PJSIP_FILE = path.join(DATA_DIR, 'custom_pjsip.conf');
const EXTENSIONS_FILE = path.join(DATA_DIR, 'custom_extensions.conf');

app.get('/api/endpoints', (req, res) => {
    if (fs.existsSync(ENDPOINTS_FILE)) {
        res.json(JSON.parse(fs.readFileSync(ENDPOINTS_FILE)));
    } else {
        res.json([]);
    }
});

app.post('/api/endpoints', (req, res) => {
    const endpoints = req.body;
    fs.writeFileSync(ENDPOINTS_FILE, JSON.stringify(endpoints, null, 2));
    
    // Generate custom_pjsip.conf
    let pjsipConfig = `
[global]
type=global
user_agent=HA-Asterisk
endpoint_identifier_order=auth_username,username,ip

`;
    let extensionsConfig = '; Auto-generated by Asterisk Web UI\n\n';
    
    endpoints.forEach(ep => {
        if (!ep.username || !ep.extension) {
            console.error('[ERROR] Skipping invalid endpoint:', ep);
            return;
        }

        pjsipConfig += `
[${ep.username}]
type=endpoint
context=support
disallow=all
allow=opus
allow=ulaw
allow=alaw
dtls_auto_generate_cert=yes
webrtc=yes
media_encryption=dtls
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
aors=${ep.username}-aor
transport=transport-ws
identify_by=auth_username
callerid="${ep.name}" <${ep.extension}>

[${ep.username}-auth]
type=auth
auth_type=userpass
username=${ep.username}
password=${ep.password}

[${ep.username}-aor]
type=aor
max_contacts=5
remove_existing=yes
`;
        // Generate dialplan for the new extension
        extensionsConfig += `exten => ${ep.extension},1,NoOp(Calling ${ep.name})\n`;
        extensionsConfig += ` same => n,Dial(PJSIP/${ep.username},60,r)\n`;
        extensionsConfig += ` same => n,Hangup()\n\n`;
    });

    try {
        fs.writeFileSync(PJSIP_FILE, pjsipConfig);
        fs.writeFileSync(EXTENSIONS_FILE, extensionsConfig);

        // Reload Asterisk seamlessly
        console.log(`[DEBUG] Wrote pjsip.conf to ${PJSIP_FILE}`);
        exec('asterisk -rx "core reload" && asterisk -rx "module reload res_pjsip.so"', (error, stdout, stderr) => {
            if (error) {
                console.error('[ERROR] Failed to reload Asterisk:', stderr);
                return res.status(500).json({ success: false, error: stderr });
            }
            res.json({ success: true, message: 'Endpoints saved and Asterisk fully reloaded (core + module).' });
        });
    } catch (e) {
        res.status(500).json({ success: false, error: e.message });
    }
});

const PORT = 8090;
app.listen(PORT, '0.0.0.0', () => {
    console.log(`[ASTERISK-UI] Web UI listening on port ${PORT}`);
});
